### ISSUE TITLE
Run yarn and complains  %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by axinging** [kmamal/gpu#1]
Hi, I am tryng to run your project on windows, however, it complains when running yarn:
```
CMake Error at CMakeLists.txt:24 (project):
  Running

   'D:/dawn-node/depot_tools/ninja' '--version'

  failed with:

   %1 is not a valid Win32 application

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
node:internal/errors:841
  const err = new Error(message);
```
Do you have any special tool setup to workaround this?
(I have workaround  CMAKE_C_COMPILER  related issue with -DCMAKE_CXX_COMPILER flag)

**Comment by axinging** [comment]
Thanks @kmamal. I am running this on a 64 bit windows machine. I build this with MINGW64/Git bash.

BTW, I also follow this(https://dawn.googlesource.com/dawn/+/refs/heads/chromium/4959/src/dawn/node/), got the same error:
```
mkdir <build-output-path>
cd <build-output-path>
cmake <dawn-root-path> -GNinja -DDAWN_BUILD_NODE_BINDINGS=1 -DDAWN_ENABLE_PIC=1 -DDAWN_USE_X11=OFF
ninja dawn.node
```
So could you please share some background how you build dawn?

**Comment by kmamal** [comment]
@axinging I need to know a bit more about what steps you take. Do you just clone this repo and run `yarn` in it? When yarn fails it's supposed to write a `yarn-error.log` file to the project directory. Even if there is no such file there should be more output from the yarn command. Please attach all of it.

For all platforms I use the included `scripts/` to build the project. The `scripts/install.mjs` script is the entrypoint and runs automatically when you run `yarn`. It will first try to download the prebuilt binaries from github, and if that fails, it will then try to build from source using the `scripts/build.mjs` script.

I don't have direct access to a windows machine so I use GitHub Actions to build for windows. I'm using MSVC instead of MinGW. On the GitHub-hosted machine I have to define a few environment variables to get it to compile, but this is a very different problem from the one you are having (you can see everything I do in the workflow file: https://github.com/kmamal/gpu/blob/master/.github/workflows/release.yml).

**Comment by axinging** [comment]
I tried to build dawn-node with below commands, it complains "%1 is not a valid Win32 application":
```
mkdir <build-output-path>
cd <build-output-path>
cmake <dawn-root-path> -GNinja -DDAWN_BUILD_NODE_BINDINGS=1 -DDAWN_ENABLE_PIC=1 -DDAWN_USE_X11=OFF
ninja dawn.node
```

I noticed that the error happens at dawn\CMakeLists.txt, when it calls project:
```
project(
    Dawn
    DESCRIPTION "Dawn, a WebGPU implementation"
    LANGUAGES C CXX
)
```

I also forked your project, and in "[Windows (x64)](https://github.com/axinging/gpu/actions/runs/5538100376/jobs/10107685424#logs)", the same error happens:
```
________ running 'download_from_google_storage --no_resume --no_auth --bucket chromium-nodejs/16.13.0 5ef847033c517c499f56f9d136d159b663bab717 -o third_party/node/node.exe' in 'D:\a\gpu\gpu\dawn\.'
0> Downloading third_party/node/node.exe@5ef847033c517c499f56f9d136d159b663bab717...

Downloading 1 files took 3.097120 second(s)

gclient(1848) _WriteFileContents:Writing to file D:\a\gpu\gpu\dawn\.gclient_previous_sync_commits
configure build in D:\a\gpu\gpu\build
CMake Error at CMakeLists.txt:24 (project):
  Running

   'D:/a/gpu/gpu/depot_tools/ninja' '--version'

  failed with:

   %1 is not a valid Win32 application


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: cmake -S "D:\a\gpu\gpu\dawn" -B "D:\a\gpu\gpu\build" -GNinja -DCMAKE_BUILD_TYPE=Release -DDAWN_BUILD_NODE_BINDINGS=1 -DDAWN_ENABLE_PIC=1
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at file:///D:/a/gpu/gpu/scripts/configure.mjs:43:1 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 5896,
  stdout: null,
  stderr: null
}

Node.js v18.16.1
npm ERR! code 1
npm ERR! path D:\a\gpu\gpu
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c cd scripts && node install.mjs

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2023-07-13T01_33_38_606Z-debug-0.log
node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: npm install
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at file:///D:/a/gpu/gpu/scripts/release.mjs:5:1 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2032,
  stdout: null,
  stderr: null
}
```

**Comment by axinging** [comment]
BTW, I make this works by using chromium\third_party\ninja\ninja.exe instead.

**Comment by axinging** [comment]
BTW, I make this works by using chromium\third_party\ninja\ninja.exe instead. So I am going to close this issue. Feel free to reopen it. Thanks!
